# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: knaumov <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/09/10 09:50:35 by knaumov           #+#    #+#              #
#    Updated: 2018/11/26 18:07:48 by knaumov          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
FILES = ./ft_atoi.c \
		./ft_bzero.c \
		./ft_isalnum.c \
		./ft_isalpha.c \
		./ft_isascii.c \
		./ft_isdigit.c \
		./ft_isprint.c \
		./ft_itoa.c \
		./ft_memalloc.c \
		./ft_memccpy.c \
		./ft_memchr.c \
		./ft_memcmp.c \
		./ft_memcpy.c \
		./ft_memdel.c \
		./ft_memmove.c \
		./ft_memset.c \
		./ft_putchar.c \
		./ft_putchar_fd.c \
		./ft_putendl.c \
		./ft_putendl_fd.c \
		./ft_putnbr.c \
		./ft_putnbr_fd.c \
		./ft_putstr.c \
		./ft_putstr_fd.c \
		./ft_strcat.c \
		./ft_strsch.c \
		./ft_strchr.c \
		./ft_strclr.c \
		./ft_strcmp.c \
		./ft_strcpy.c \
		./ft_strdel.c \
		./ft_strdup.c \
		./ft_strequ.c \
		./ft_striter.c \
		./ft_striteri.c \
		./ft_strjoin.c \
		./ft_strlcat.c \
		./ft_strlen.c \
		./ft_strmap.c \
		./ft_strmapi.c \
		./ft_strncat.c \
		./ft_strncmp.c \
		./ft_strncpy.c \
		./ft_strnequ.c \
		./ft_strnew.c \
		./ft_strnstr.c \
		./ft_strrchr.c \
		./ft_strsplit.c \
		./ft_strstr.c \
		./ft_strsub.c \
		./ft_strtrim.c \
		./ft_tolower.c \
		./ft_toupper.c \
		./ft_itoa_base.c \
		./get_next_line.c \
		./ft_putunsignedint.c \
		./ft_strccrt.c \
		./ft_bchar.c \
		./ft_update.c \
		./ft_strtoupper.c \
		./ft_strtolower.c \
		./ft_putwchar.c \
		./ft_putwchar_fd.c \
		./ft_putwstr.c \
		./ft_putwstr_fd.c \
		./ft_wstrlen.c \
		./ft_wstrdup.c \
		./ft_wchrlen.c \
		./ft_strcon.c \
		./ft_clean_arr.c \
		./ft_create_arr.c \
		./ft_printf/adding_minus.c \
		./ft_printf/adding_plus.c \
		./ft_printf/adding_precision_number.c \
		./ft_printf/adding_precision_string.c \
		./ft_printf/adding_space.c \
		./ft_printf/adding_width.c \
		./ft_printf/adding_width_null_char.c \
		./ft_printf/conversion_b.c \
		./ft_printf/conversion_c.c \
		./ft_printf/conversion_d_i.c \
		./ft_printf/conversion_o_cap_o.c \
		./ft_printf/conversion_p.c \
		./ft_printf/conversion_s.c \
		./ft_printf/conversion_u_cap_d_cap_u.c \
		./ft_printf/conversion_wide_c.c \
		./ft_printf/conversion_wide_s.c \
		./ft_printf/conversion_x_cap_x.c \
		./ft_printf/conversions.c \
		./ft_printf/ft_itoa_base_unsigned.c \
		./ft_printf/ft_itoa_intmax.c \
		./ft_printf/ft_itoa_unsigned.c \
		./ft_printf/ft_printf.c \
		./ft_printf/handle_flags.c \
		./ft_printf/handle_format.c \
		./ft_printf/handle_precision.c \
		./ft_printf/handle_width.c \
		./ft_printf/parse_flags.c \
		./ft_printf/printing_wide_string.c

OBJ =   ./ft_atoi.o \
		./ft_bzero.o \
		./ft_isalnum.o \
		./ft_isalpha.o \
		./ft_isascii.o \
		./ft_isdigit.o \
		./ft_isprint.o \
		./ft_itoa.o \
		./ft_memalloc.o \
		./ft_memccpy.o \
		./ft_memchr.o \
		./ft_memcmp.o \
		./ft_memcpy.o\
		./ft_memdel.o \
		./ft_memmove.o \
		./ft_memset.o \
		./ft_putchar.o \
		./ft_putchar_fd.o \
		./ft_putendl.o \
		./ft_putendl_fd.o \
		./ft_putnbr.o \
		./ft_putnbr_fd.o \
		./ft_putstr.o \
		./ft_putstr_fd.o \
		./ft_strcat.o \
		./ft_strsch.o \
		./ft_strchr.o \
		./ft_strclr.o \
		./ft_strcmp.o \
		./ft_strcpy.o \
		./ft_strdel.o \
		./ft_strdup.o \
		./ft_strequ.o \
		./ft_striter.o \
		./ft_striteri.o \
		./ft_strjoin.o \
		./ft_strlcat.o \
		./ft_strlen.o \
		./ft_strmap.o \
		./ft_strmapi.o \
		./ft_strncat.o \
		./ft_strncmp.o \
		./ft_strncpy.o \
		./ft_strnequ.o \
		./ft_strnew.o \
		./ft_strnstr.o \
		./ft_strrchr.o \
		./ft_strsplit.o \
		./ft_strstr.o \
		./ft_strsub.o \
		./ft_strtrim.o \
		./ft_tolower.o \
		./ft_toupper.o \
		./ft_itoa_base.o \
		./get_next_line.o \
		./ft_putunsignedint.o \
		./ft_strccrt.o \
		./ft_bchar.o \
		./ft_update.o \
		./ft_strtoupper.o \
		./ft_strtolower.o \
		./ft_putwchar.o \
		./ft_putwchar_fd.o \
		./ft_putwstr.o \
		./ft_putwstr_fd.o \
		./ft_wstrlen.o \
		./ft_wstrdup.o \
		./ft_wchrlen.o \
		./ft_strcon.o \
		./adding_minus.o \
		./adding_plus.o \
		./adding_precision_number.o \
		./adding_precision_string.o \
		./adding_space.o \
		./adding_width.o \
		./adding_width_null_char.o \
		./conversion_b.o \
		./conversion_c.o \
		./conversion_d_i.o \
		./conversion_o_cap_o.o \
		./conversion_p.o \
		./conversion_s.o \
		./conversion_u_cap_d_cap_u.o \
		./conversion_wide_c.o \
		./conversion_wide_s.o \
		./conversion_x_cap_x.o \
		./conversions.o \
		./ft_itoa_base_unsigned.o \
		./ft_itoa_intmax.o \
		./ft_itoa_unsigned.o \
		./ft_printf.o \
		./handle_flags.o \
		./handle_format.o \
		./handle_precision.o \
		./handle_width.o \
		./parse_flags.o \
		./printing_wide_string.o \
		./ft_clean_arr.o \
		./ft_create_arr.o

RESET = \033[0m
RED = \033[0;31m
GREEN = \033[0;32m
BLUE = \033[0;36m
RED_EXTRA = \033[1;31m
GREEN_EXTRA = \033[1;32m
BLUE_EXTRA = \033[1;36m

all: $(NAME)

$(NAME):
	@echo "$(GREEN_EXTRA)   Libft: $(GREEN)Making objects for $(GREEN_EXTRA)libft.a$(RESET)"
	@gcc -Wall -Wextra -Werror -c $(FILES)
	@echo "$(GREEN_EXTRA)   Libft: $(GREEN)Compiling $(GREEN_EXTRA)libft.a$(RESET)"
	@ar rc $(NAME) $(OBJ)
	@ranlib $(NAME)
	@echo "$(BLUE_EXTRA)   Libft: $(NAME)$(BLUE): Complete$(RESET)"

clean:
	@if [ -a "./ft_atoi.o" ]; then echo "$(RED_EXTRA)   Libft: $(RED)Deleting objects for $(RED_EXTRA)libft.a$(RESET)"; fi
	@if [ -a "./ft_atoi.o" ]; then /bin/rm -f $(OBJ); fi
	@echo "$(BLUE_EXTRA)   Libft: clean$(BLUE): Complete$(RESET)"

fclean: clean
	@if [ -a "$(NAME)" ]; then echo "$(RED_EXTRA)   Libft: $(RED)Deleting $(RED_EXTRA)libft.a$(RESET)"; fi
	@if [ -a "$(NAME)" ]; then /bin/rm -f $(NAME); fi
	@echo "$(BLUE_EXTRA)   Libft: fclean$(BLUE): Complete$(RESET)"

re:	fclean all
